version: '3.2'

services:
  broker:
    image: confluentinc/cp-kafka:7.0.1
    container_name: broker
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper
    env_file:
      - .env
  zookeeper:
    image: confluentinc/cp-zookeeper:7.0.1
    env_file:
      - .env

  api:
    container_name: api
    build:
      context: .
      dockerfile: api-service/Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - storage
    env_file:
          - api-service/.env
    restart: always

  storage:
    container_name: storage
    build:
      context: .
      dockerfile: storage-service/Dockerfile
    depends_on:
      - broker
      - postgres
    env_file:
      - storage-service/.env
    restart: always

  postgres:
    image: 'postgres:latest'
    container_name: postgresdb
    env_file:
      - .env
    volumes:
      - ./db-data:/var/lib/postgresql/data/